# backup-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  namespace: student-259337
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/backup"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: student-259337
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
