apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: student-259337
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sdzol/backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGODB_HOST
          livenessProbe:
            httpGet:
              path: /up
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /up
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10