apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: student-259337
spec:
  schedule: "30 1,3,5 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongo-backup
              image: mongo
              command: ["sh", "-c", "mongodump --uri=mongodb://mongodb-headless:27017 --out=/backup"]
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc